# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/chiro/programs/urllc-chisel/xdc/generic/generic.xdc

# XDC: /home/chiro/programs/urllc-chisel/xdc/generic/urllc.xdc

# XDC: /home/chiro/programs/urllc-chisel/xdc/Receiver.xdc

# Block Designs: bd/design_receiver/design_receiver.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_receiver || ORIG_REF_NAME==design_receiver} -quiet] -quiet

# IP: bd/design_receiver/ip/design_receiver_clk_wiz_0_0/design_receiver_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_receiver_clk_wiz_0_0 || ORIG_REF_NAME==design_receiver_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_receiver/ip/design_receiver_ReceiverWrapper_0_0/design_receiver_ReceiverWrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_receiver_ReceiverWrapper_0_0 || ORIG_REF_NAME==design_receiver_ReceiverWrapper_0_0} -quiet] -quiet

# XDC: bd/design_receiver/design_receiver_ooc.xdc
