# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/chiro/programs/urllc-chisel/xdc/generic/generic.xdc

# XDC: /home/chiro/programs/urllc-chisel/xdc/generic/urllc.xdc

# XDC: /home/chiro/programs/urllc-chisel/xdc/Sender.xdc

# Block Designs: bd/design_sender/design_sender.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_sender || ORIG_REF_NAME==design_sender} -quiet] -quiet

# IP: bd/design_sender/ip/design_sender_SenderWrapper_0_0/design_sender_SenderWrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_sender_SenderWrapper_0_0 || ORIG_REF_NAME==design_sender_SenderWrapper_0_0} -quiet] -quiet

# IP: bd/design_sender/ip/design_sender_clk_wiz_0_0/design_sender_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_sender_clk_wiz_0_0 || ORIG_REF_NAME==design_sender_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/design_sender/design_sender_ooc.xdc
