# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Programs/urllc-chisel/xdc/generic/generic.xdc

# XDC: D:/Programs/urllc-chisel/xdc/generic/urllc.xdc

# XDC: D:/Programs/urllc-chisel/xdc/Connect.xdc

# Block Designs: bd/design_connect/design_connect.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_connect || ORIG_REF_NAME==design_connect} -quiet] -quiet

# IP: bd/design_connect/ip/design_connect_ConnectWrapper_0_0/design_connect_ConnectWrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_connect_ConnectWrapper_0_0 || ORIG_REF_NAME==design_connect_ConnectWrapper_0_0} -quiet] -quiet

# IP: bd/design_connect/ip/design_connect_clk_wiz_0_0/design_connect_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_connect_clk_wiz_0_0 || ORIG_REF_NAME==design_connect_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/design_connect/design_connect_ooc.xdc
